### ISSUE TITLE
Remove Twitter from News 

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io_old#15]

**Comment by shkodm** [comment]
You mean from the "Latest updates" ? What is the problem with it?

**Comment by fsimonis** [comment]
> preCICE is now on Twitter: Follow us at @preCICE_org to always stay up-to-date!

"Now" is a long time ago. The social icon in the footer suffices.

**Comment by MakisH** [comment]
Does not apply in the [new website](https://github.com/precice/precice.github.io).
