### ISSUE TITLE
Add a fancy Hero

### ISSUE THREAD

**Issue by fsimonis** [precice/precice.github.io_old#22]
Add a fancy Hero with some images from our test cases to the front page.

**Comment by MakisH** [comment]
What is a Hero in this context?

**Comment by fsimonis** [comment]
@MakisH https://en.wikipedia.org/wiki/Hero_image

**Comment by uekerman** [comment]
We could reuse some "heros" from http://coplon.de/

**Comment by MakisH** [comment]
This is essentially closed in the [new website](https://github.com/precice/precice.github.io).
