### ISSUE TITLE
Testimonial not rendered correctly

### ISSUE THREAD

**Issue by MakisH** [precice/precice.github.io_old#44]
[This testimonial](https://github.com/precice/precice.github.io/blob/35902ffda18589a1c8dfd099cbdf770e43110b11/_testimonials/08-WindEnergyDelft.md) is missing its title and figure (see [precice.org](https://www.precice.org/testimonials/)).

I tried to find out what is going wrong, but the data file looks correct. Interestingly, it is also rendered differently on GitHub.

**Comment by fsimonis** [comment]
Fixed :wink:
