### ISSUE TITLE
Link to FAQ on Discourse broken

### ISSUE THREAD

**Issue by ajaust** [precice/precice.github.io_old#70]
The [FAQ page](https://www.precice.org/faq/) is referring to the Discourse page [https://precice.discourse.group/tags/faq](https://precice.discourse.group/tags/faq). However, the page on Discourse does not exist (anymore?)

```
Oops! That page doesn’t exist or is private.
```

**Comment by MakisH** [comment]
The link works for me, also in private mode. Could you try again? Maybe it was a temporary issue.

**Comment by ajaust** [comment]
I can confirm that it works now.
